name: "Composer Require Checker"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  composer-require-checker:
    name: "Composer Require Checker"
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "7.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Get Composer cache directory"
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-dir)"

      - name: "Cache dependencies"
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}
          restore-keys: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Install require checker"
        run: "composer require --dev maglnet/composer-require-checker"

      - name: "Check"
        run: "vendor/bin/composer-require-checker check"
